package com.example.wikimusic

class Artist(val idArtist: String?,
                val strArtist: String?,
                val strArtistStripped: String?,
                val strArtistAlternate: String?,
                val strLabel: String?,
                val idLabel: String?,
                val intFormedYear: String?,
                val intBornYear: String?,
                val intDiedYear: String?,
                val strDisbanded: String?,
                val strStyle: String?,
                val strGenre: String?,
                val strMood: String?,
                val strWebsite: String?,
                val strFacebook: String?,
                val strTwitter: String?,
                val strBiographyEN: String?,
                val strBiographyDE: String?,
                val strBiographyFR: String?,
                val strBiographyCN: String?,
                val strBiographyIT: String?,
                val strBiographyJP: String?,
                val strBiographyRU: String?,
                val strBiographyES: String?,
                val strBiographyPT: String?,
                val strBiographySE: String?,
                val strBiographyHU: String?,
                val strBiographyNO: String?,
                val strBiographyIL: String?,
                val strBiographyPL: String?,
                val strGender: String?,
                val intMembers: String?,
                val strCountry: String?,
                val strCountryCode: String?,
                val strArtistThumb: String?,
                val strArtistLogo: String?,
                val strArtistClearart: String?,
                val strArtistWideThumb: String?,
                val strArtistFanart: String?,
                val strArtistFanart2: String?,
                val strArtistFanart3: String?,
                val strArtistFanart4: String?,
                val strArtistBanner: String?,
                val strMusicBrainzID: String?,
                val strISNIcode: String?,
                val strLastFMChart: String?,
                val intCharted: String?,
                val strLocked: String?
) {
}